### ISSUE TITLE
执行./build_android.sh时候提示no such file or directory

### ISSUE THREAD

**Issue by BigImpostor** [wanliyang1990/FFmpeg-Android#1]
你好，我在掘金上看到了你的教程，在执行./build_android.sh时候提示no such file or directory，可是我根目录下的确有我上传的build_android.sh啊，请问这是为什么啊

**Comment by ywl5320** [comment]
你好，build_android.sh你是怎么创建的，要在linux里面创建，不要在windows里面创建，还有要设置权限

**Comment by BigImpostor** [comment]
谢谢，我昨晚找到原因了，就是因为我的build_android.sh实在windows里创建的，后来改了格式之后就可以了。

**Comment by ywl5320** [comment]
嗯 可以了就行
